{% set name = "cpplint" %}
{% set version = "1.5.1" %}
{% set sha256 = "f47ee33b7bf3d4d359399802502361890e869c2125f31d3a42c04bf28010d336" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cpplint/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - cpplint = cpplint:main

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - cpplint

about:
  description: |
    Cpplint is a command-line tool to check C/C++ files for style issues
    following Google's C++ style guide. Cpplint is developed and maintained by
    Google Inc. at google/styleguide, also see see the wikipedia entry.

    While Google maintains cpplint, Google is not (very) responsive to issues
    and pull requests, this fork aims to be (somewhat) more open to add fixes to
    cpplint to enable fixes, when those fixes make cpplint usable in wider
    contexts.
  home: https://github.com/cpplint/cpplint
  dev_url: https://github.com/cpplint/cpplint
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A publicly maintained version of Google's static analysis tool for C/C++ code.

extra:
  recipe-maintainers:
    - tovrstra
